// <auto-generated />
using System;
using Cargo.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cargo.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CargoContext))]
    [Migration("20220403220603_PoolsAndAwbNumbersTables")]
    partial class PoolsAndAwbNumbersTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.Awb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AcPrefix")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("AcPrefix");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Destination");

                    b.Property<string>("ManifestDescriptionOfGoods")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ManifestDescriptionOfGoods");

                    b.Property<int>("NumberOfPieces")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfPieces");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Origin");

                    b.Property<string>("QuanDetShipmentDescriptionCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("QuanDetShipmentDescriptionCode");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("SpecialHandlingRequirements")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("SpecialHandlingRequirements");

                    b.Property<string>("SpecialServiceRequest")
                        .HasMaxLength(65)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("SpecialServiceRequest");

                    b.Property<decimal>("VolumeAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("VolumeAmount");

                    b.Property<string>("VolumeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("VolumeCode");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Weight");

                    b.Property<string>("WeightCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("WeightCode");

                    b.HasKey("Id");

                    b.ToTable("Awbs");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.AwbNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateDate");

                    b.Property<int>("PoolId")
                        .HasColumnType("int");

                    b.Property<int>("SerialNumber")
                        .HasMaxLength(7)
                        .HasColumnType("int")
                        .HasColumnName("SerialNumber");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.ToTable("AwbNumber");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AwbId")
                        .HasColumnType("int")
                        .HasColumnName("AwbId");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("FlightId")
                        .HasColumnType("int")
                        .HasColumnName("FlightId");

                    b.Property<string>("ForwardingAgent")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("ForwardingAgent");

                    b.Property<int?>("ForwardingAgentId")
                        .HasColumnType("int")
                        .HasColumnName("ForwardingAgentId");

                    b.Property<string>("SpaceAllocationCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("SpaceAllocationCode");

                    b.Property<string>("Unloading")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Unloading");

                    b.HasKey("Id");

                    b.HasIndex("AwbId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int")
                        .HasColumnName("CarrierId");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateClose");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DateOpen");

                    b.Property<int>("PoolLenght")
                        .HasColumnType("int")
                        .HasColumnName("PoolLenght");

                    b.Property<int>("SaleAgentId")
                        .HasColumnType("int")
                        .HasColumnName("SaleAgentId");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int")
                        .HasColumnName("StartNumber");

                    b.Property<string>("Status")
                        .HasColumnType("longtext")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Pool");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.AwbNumber", b =>
                {
                    b.HasOne("Cargo.Infrastructure.Data.Model.Pool", "Pool")
                        .WithMany("UsedAwbNumbers")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.Booking", b =>
                {
                    b.HasOne("Cargo.Infrastructure.Data.Model.Awb", "Awb")
                        .WithMany("Bookings")
                        .HasForeignKey("AwbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Awb");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.Awb", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Cargo.Infrastructure.Data.Model.Pool", b =>
                {
                    b.Navigation("UsedAwbNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
